List
bobmayuze/Vercipe pull request #46
Opened 2018-03-27 22:54 UTC by limaa1

2018-03-27 22:56 UTC, limaa1 commented
Navbar:
- searchbox: type in recipe name, press enter to search
- create button: click to navigate to create-board
- my recipes: click to navigate to dashboard

2018-03-27 23:43 UTC, bobmayuze requested changes
Great work! I really like the updated UI, tho we might need to think about the mobile part. There are some small problems in current pr

2018-03-27 23:43 UTC, bobmayuze commented on vercipe_frontend/frontend/src/app/common/header/header.component.css
> +/*.signin-content {
Remove the code if it is not necessary

2018-03-27 23:43 UTC, bobmayuze commented on vercipe_frontend/frontend/src/app/create-board/create-board.component.html
> +         (keydown.enter)="addMat()">
When a new input filed is added, we need to make the type focus to that part rather than stay in the same one

2018-03-27 23:43 UTC, bobmayuze commented on vercipe_frontend/frontend/src/app/dashboard/dashboard.component.html
> +    <p>Name: {{creator.name}}</p>
seems to be not working properly

2018-03-27 23:43 UTC, bobmayuze commented on vercipe_frontend/frontend/src/app/dashboard/dashboard.component.html
> +<!-- <div id="dashboard" class="container-fluid">
Remove it if it is not necessary

2018-03-28 02:22 UTC, alimabean commented on vercipe_frontend/frontend/src/app/common/header/header.component.css
> +/*.signin-content {
fixed

2018-03-28 13:36 UTC, bobmayuze commented
The detail board isn't really working

2018-03-28 14:25 UTC, bobmayuze approved these changes

2018-03-28 14:25 UTC, bobmayuze commented on vercipe_frontend/frontend/src/app/detail-board/detail-board.component.ts
> +    goBack = () => {
use 
```
  goBack(): void {
    this.location.back();
  }
```

2018-03-28 14:25 UTC, bobmayuze commented on vercipe_frontend/frontend/src/app/detail-board/detail-board.component.ts
> +        })
missing `;`

2018-03-28 18:43 UTC, merged